apiVersion: v1
kind: Secret
metadata:
  name: {{ include "where-we-are.fullname" . }}
  labels:
    {{- include "where-we-are.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY_BASE: {{ .Values.secretKeyBase | default (randAlphaNum 64) | quote }}
  CALDAV_PASSWORD: {{ .Values.caldav.password | default "" | quote }}
