apiVersion: v1
kind: Secret
metadata:
  name: {{ include "where-we-are.fullname" . }}
  labels:
    {{- include "where-we-are.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key-base: {{ required "app.secretKeyBase must be set (mix phx.gen.secret)" .Values.app.secretKeyBase | b64enc | quote }}
  {{- if .Values.app.caldav.username }}
  caldav-username: {{ .Values.app.caldav.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.app.caldav.password }}
  caldav-password: {{ .Values.app.caldav.password | b64enc | quote }}
  {{- end }}
